[project]
name = "studies"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "jinja2>=3.1.6",
    "lxml>=6.0.2",
    "pycmarkgfm>=1.2.1",
    "requests>=2.32.5",
]
